# Generated by Django 4.2.16 on 2024-09-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_organizer_alter_event_sponsors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sponsors',
        ),
    ]
