# Generated by Django 4.2.16 on 2024-09-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_sponsorship_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorshiptier',
            old_name='benfits',
            new_name='benefits',
        ),
    ]
