# Generated by Django 4.2.16 on 2024-09-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_benfits_sponsorshiptier_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'conference'), ('workshop', 'workshop'), ('webinar', 'webinar'), ('networking', 'networking'), ('sports', 'sports'), ('music', 'music'), ('art', 'art')], max_length=100),
        ),
    ]
