# Generated by Django 4.2.16 on 2024-09-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorship',
            old_name='date_joined',
            new_name='date_sponsored',
        ),
    ]
