# Generated by Django 4.2.16 on 2024-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_rename_date_joined_sponsorship_date_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_count',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
