# Generated by Django 4.2.16 on 2024-09-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='events/brochure'),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='events/display_picture'),
        ),
    ]
