# Generated by Django 4.2.16 on 2024-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_customuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_organizer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_sponsor',
            field=models.BooleanField(null=True),
        ),
    ]
